package ${pkg};

import com.landaojia.blogserver.dao.MybatisDAO;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
public abstract class ${table.className}Dao extends MybatisDAO<${table.className}> {
	
	protected String buildStatementName(String suffix) {
		return ${table.className}Dao.class.getName() + "." + suffix;
	}

}
