package com.landaojia.blogserver.dao.user;


import com.landaojia.blogserver.common.dao.MybatisDAO;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
public abstract class AbsUserDao extends MybatisDAO<User> {
	
	protected String buildStatementName(String suffix) {
		return AbsUserDao.class.getName() + "." + suffix;
	}

}
