package com.landaojia.blogserver.dao.user;


import com.landaojia.blogserver.dao.BaseEO;

/**
 * 
 * 
 * Auto Generated by <code>CodeGenerator</code>
 */
public abstract class AbsUser extends BaseEO {
	private static final long serialVersionUID = 1L;

	private String uname;//

	private String pwd;//

	/**
	 * return 
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * @param uname
	 *            
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * return 
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * @param pwd
	 *            
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
}
