package com.landaojia.blogserver.dao.user;

import org.springframework.stereotype.Service;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
@Service
public class UserDao extends AbsUserDao {

}
