package com.landaojia.blog.post.entity;

import com.landaojia.blog.common.dao.BaseEntity;

/**
 * 
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class PostAttachment extends BaseEntity {
	private static final long serialVersionUID = 1L;

	public static final Integer FILE_TYPE_OTHER = 0;
	public static final Integer FILE_TYPE_IMG = 1;
	public static final String FILE_TYPE_IMG_DETAIL = "img bmp jpg jpeg";
	public static final Integer FILE_TYPE_OFFICE = 2;
	public static final String FILE_TYPE_OFFICE_DETAIL = "xls mdb xls doc ppt docx xlsx pptx";
	public static final Integer FILE_TYPE_VIDEO = 3;
	public static final String FILE_TYPE_VIDEO_DETAIL = "mkv avi vob mp4 mpeg4 wmv flv";

	public static Integer getFileType(String postFix) {
		if (FILE_TYPE_IMG_DETAIL.contains(postFix)) {
			return FILE_TYPE_IMG;
		} else if (FILE_TYPE_OFFICE_DETAIL.contains(postFix)) {
			return FILE_TYPE_OFFICE;
		} else if (FILE_TYPE_VIDEO_DETAIL.contains(postFix)) {
			return FILE_TYPE_VIDEO;
		} else
			return FILE_TYPE_OTHER;
	}

	private Long postId;//

	private String fileName;//

	private String fileOriginalName;//

	private Integer fileType;//

	private Long fileSize;//

	/**
	 * return
	 */
	public Long getPostId() {
		return postId;
	}

	/**
	 * @param postId
	 * 
	 */
	public void setPostId(Long postId) {
		this.postId = postId;
	}

	/**
	 * return
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * @param fileName
	 * 
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * return
	 */
	public String getFileOriginalName() {
		return fileOriginalName;
	}

	/**
	 * @param fileOriginalName
	 * 
	 */
	public void setFileOriginalName(String fileOriginalName) {
		this.fileOriginalName = fileOriginalName;
	}

	/**
	 * return
	 */
	public Integer getFileType() {
		return fileType;
	}

	/**
	 * @param fileType
	 * 
	 */
	public void setFileType(Integer fileType) {
		this.fileType = fileType;
	}

	public Long getFileSize() {
		return fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}


}