package com.landaojia.blogserver.dao.user;

import com.landaojia.blogserver.dao.MybatisDAO;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
public abstract class UserDao extends MybatisDAO<User> {
	
	protected String buildStatementName(String suffix) {
		return UserDao.class.getName() + "." + suffix;
	}

}
