package com.landaojia.blog.user.entity;

import com.landaojia.blog.common.dao.BaseEntity;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
public class User extends BaseEntity {

    private static final long serialVersionUID = 1L;
    private String userName;//
    
    private String email;//

    private String cryptedPassword;//

    private String role;//
    
    private String accessToken;//

    
    public User() {
        super();
    }

    public User(String userName) {
        super();
        this.userName = userName;
    }
    
    public User(String userName, String cryptedPassword) {
        super();
        this.userName = userName;
        this.cryptedPassword = cryptedPassword;
    }

    /**
     * return
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName
     */
    public User setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * return
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email
     */
    public User setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * return
     */
    public String getCryptedPassword() {
        return cryptedPassword;
    }

    /**
     * @param cryptedPassword
     */
    public void setCryptedPassword(String cryptedPassword) {
        this.cryptedPassword = cryptedPassword;
    }

    /**
     * return
     */
    public String getRole() {
        return role;
    }

    /**
     * @param role
     */
    public void setRole(String role) {
        this.role = role;
    }

    
    public String getAccessToken() {
        return accessToken;
    }

    
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }
}
